<?php

namespace TuyMedio\Bundle\GradoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradoRepository extends EntityRepository
{
}
