services:
    tuy_medio_alumno.admin.alumno:
        class: TuyMedio\Bundle\AlumnoBundle\Admin\AlumnoAdmin
        arguments: [~, TuyMedio\Bundle\AlumnoBundle\Entity\Alumno, TuyMedioAlumnoBundle:AlumnoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Alumno}
