services:
    tuy_medio_grado.admin.grado:
        class: TuyMedio\Bundle\GradoBundle\Admin\GradoAdmin
        arguments: [~, TuyMedio\Bundle\GradoBundle\Entity\Grado, TuyMedioGradoBundle:GradoAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Grado}
