<?php

namespace TuyMedio\Bundle\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @author Ramón Serrano <ramon.calle.88@gmail.com>
 */
class UsuarioRepository extends EntityRepository
{
}
